# Generated by Django 6.0.1 on 2026-04-01 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_alter_project_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entry',
            name='comment',
        ),
        migrations.AddField(
            model_name='comment',
            name='comment',
            field=models.ManyToManyField(to='project.entry'),
        ),
    ]
