# Generated by Django 6.0.1 on 2026-04-01 09:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0003_remove_entry_comment_comment_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='comment',
        ),
    ]
