# Generated by Django 6.0.1 on 2026-04-01 09:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0005_remove_entry_likes_comment_entry_like'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='Entry',
            new_name='entry',
        ),
    ]
