# Generated by Django 6.0.1 on 2026-04-04 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0010_alter_userachievement_achievement'),
    ]

    operations = [
        migrations.AddField(
            model_name='streaks',
            name='last_entry_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
