# Generated by Django 6.0.1 on 2026-04-04 07:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_githubprofile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='followers',
            new_name='total_points',
        ),
    ]
